const Cars = [
    // Maruti Suzuki
    {
        id: 1,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Omni",
        tyre_brand: "Apollo",
        tyre_model: "Amazer XL",
        tyre_size: "145R12 6PR LT",
        price: "₹0"
    },
    {
        id: 2,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Omni",
        tyre_brand: "JK",
        tyre_model: "Ultima NXT",
        tyre_size: "145R12 6PR LT",
        price: "₹0"
    },
    {
        id: 3,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Omni",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "145R12 6PR LT",
        price: "₹0"
    },
    {
        id: 4,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Alto",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 4G",
        tyre_size: "145/80R12 74T",
        price: "₹0"
    },
    {
        id: 5,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Alto",
        tyre_brand: "JK",
        tyre_model: "Ultima NXT",
        tyre_size: "145/80R12 74T",
        price: "₹0"
    },
    {
        id: 6,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Alto",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "145/80R12 74T",
        price: "₹0"
    },
    {
        id: 7,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 8,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 9,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift",
        tyre_brand: "Bridgestone",
        tyre_model: "B250",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 10,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Baleno",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "185/65R15 88S",
        price: "₹0"
    },
    {
        id: 11,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Baleno",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "185/65R15 88S",
        price: "₹0"
    },
    {
        id: 12,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Baleno",
        tyre_brand: "Bridgestone",
        tyre_model: "Turanza T001",
        tyre_size: "185/65R15 88S",
        price: "₹0"
    },
    {
        id: 13,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift Dzire",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 4G",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 14,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift Dzire",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 15,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Swift Dzire",
        tyre_brand: "Bridgestone",
        tyre_model: "B250",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 16,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Vitara Brezza",
        tyre_brand: "Apollo",
        tyre_model: "Apterra H/T2",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    {
        id: 17,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Vitara Brezza",
        tyre_brand: "JK",
        tyre_model: "Elanzo NXT",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    {
        id: 18,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Maruti Suzuki",
        vehicle_model: "Vitara Brezza",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/L 400",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    // Hyundai
    {
        id: 19,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Santro",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 4G",
        tyre_size: "155/70R13 75T",
        price: "₹0"
    },
    {
        id: 20,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Santro",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "155/70R13 75T",
        price: "₹0"
    },
    {
        id: 21,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Santro",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "155/70R13 75T",
        price: "₹0"
    },
    {
        id: 22,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i10",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 4G",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 23,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i10",
        tyre_brand: "JK",
        tyre_model: "Ultima NXT",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 24,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i10",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 25,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i20",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 26,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i20",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 27,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "i20",
        tyre_brand: "Bridgestone",
        tyre_model: "Turanza T001",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 28,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Creta",
        tyre_brand: "Apollo",
        tyre_model: "Apterra H/T2",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    {
        id: 29,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Creta",
        tyre_brand: "JK",
        tyre_model: "Elanzo NXT",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    {
        id: 30,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Hyundai",
        vehicle_model: "Creta",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    // Tata Motors
    {
        id: 31,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nano",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 3G",
        tyre_size: "135/70R12 65S",
        price: "₹0"
    },
    {
        id: 32,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nano",
        tyre_brand: "JK",
        tyre_model: "Ultima XP",
        tyre_size: "135/70R12 65S",
        price: "₹0"
    },
    {
        id: 33,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nano",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "135/70R12 65S",
        price: "₹0"
    },
    {
        id: 34,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Tiago",
        tyre_brand: "Apollo",
        tyre_model: "Amazer 4G",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 35,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Tiago",
        tyre_brand: "JK",
        tyre_model: "Ultima NXT",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 36,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Tiago",
        tyre_brand: "Bridgestone",
        tyre_model: "B290",
        tyre_size: "155/80R13 79T",
        price: "₹0"
    },
    {
        id: 37,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nexon",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    {
        id: 38,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nexon",
        tyre_brand: "JK",
        tyre_model: "Elanzo NXT",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    {
        id: 39,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Nexon",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "215/60R16 95H",
        price: "₹0"
    },
    {
        id: 40,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Altroz",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 41,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Altroz",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 42,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Altroz",
        tyre_brand: "Bridgestone",
        tyre_model: "Turanza T001",
        tyre_size: "165/80R14 85T",
        price: "₹0"
    },
    {
        id: 43,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Harrier",
        tyre_brand: "Apollo",
        tyre_model: "Apterra H/T2",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    {
        id: 44,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Harrier",
        tyre_brand: "JK",
        tyre_model: "Ranger HT",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    {
        id: 45,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Tata Motors",
        vehicle_model: "Harrier",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    // Mahindra
    {
        id: 46,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "KUV100",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 47,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "KUV100",
        tyre_brand: "JK",
        tyre_model: "Vectra",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 48,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "KUV100",
        tyre_brand: "Bridgestone",
        tyre_model: "Turanza T001",
        tyre_size: "185/65R14 86H",
        price: "₹0"
    },
    {
        id: 49,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "XUV300",
        tyre_brand: "Apollo",
        tyre_model: "Alnac 4G",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    {
        id: 50,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "XUV300",
        tyre_brand: "JK",
        tyre_model: "Elanzo NXT",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    {
        id: 51,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "XUV300",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "205/65R16 95H",
        price: "₹0"
    },
    {
        id: 52,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Scorpio",
        tyre_brand: "Apollo",
        tyre_model: "Apterra H/T2",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    {
        id: 53,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Scorpio",
        tyre_brand: "JK",
        tyre_model: "Ranger HT",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    {
        id: 54,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Scorpio",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "235/65R17 104H",
        price: "₹0"
    },
    {
        id: 55,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Thar",
        tyre_brand: "Apollo",
        tyre_model: "Apterra H/T2",
        tyre_size: "255/65R18 111S",
        price: "₹0"
    },
    {
        id: 56,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Thar",
        tyre_brand: "JK",
        tyre_model: "Ranger HT",
        tyre_size: "255/65R18 111S",
        price: "₹0"
    },
    {
        id: 57,
        image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
        vehicle_type: "Car",
        vehicle_brand: "Mahindra",
        vehicle_model: "Thar",
        tyre_brand: "Bridgestone",
        tyre_model: "Dueler H/T 400",
        tyre_size: "255/65R18 111S",
        price: "₹0"
    },
        // Honda
        {
            id: 58,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Amaze",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 59,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Amaze",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 60,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Amaze",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 61,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "City",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "185/55R16 83V",
            price: "₹0"
        },
        {
            id: 62,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "City",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "185/55R16 83V",
            price: "₹0"
        },
        {
            id: 63,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "City",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "185/55R16 83V",
            price: "₹0"
        },
        {
            id: 64,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "WR-V",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "195/60R16 89V",
            price: "₹0"
        },
        {
            id: 65,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "WR-V",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "195/60R16 89V",
            price: "₹0"
        },
        {
            id: 66,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "WR-V",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "195/60R16 89V",
            price: "₹0"
        },
        {
            id: 67,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Jazz",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "175/65R15 84T",
            price: "₹0"
        },
        {
            id: 68,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Jazz",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "175/65R15 84T",
            price: "₹0"
        },
        {
            id: 69,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Jazz",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "175/65R15 84T",
            price: "₹0"
        },
        {
            id: 70,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Civic",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "215/50R17 91V",
            price: "₹0"
        },
        {
            id: 71,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Civic",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "215/50R17 91V",
            price: "₹0"
        },
        {
            id: 72,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Honda",
            vehicle_model: "Civic",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "215/50R17 91V",
            price: "₹0"
        },
    
        // Toyota
        {
            id: 73,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Innova",
            tyre_brand: "Apollo",
            tyre_model: "Apterra H/T2",
            tyre_size: "205/65R15 99H",
            price: "₹0"
        },
        {
            id: 74,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Innova",
            tyre_brand: "JK",
            tyre_model: "Ranger HT",
            tyre_size: "205/65R15 99H",
            price: "₹0"
        },
        {
            id: 75,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Innova",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/T 400",
            tyre_size: "205/65R15 99H",
            price: "₹0"
        },
        {
            id: 76,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Fortuner",
            tyre_brand: "Apollo",
            tyre_model: "Apterra H/T2",
            tyre_size: "265/65R17 112S",
            price: "₹0"
        },
        {
            id: 77,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Fortuner",
            tyre_brand: "JK",
            tyre_model: "Ranger HT",
            tyre_size: "265/65R17 112S",
            price: "₹0"
        },
        {
            id: 78,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Fortuner",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/T 400",
            tyre_size: "265/65R17 112S",
            price: "₹0"
        },
        {
            id: 79,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Etios",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 80,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Etios",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 81,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Etios",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 82,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Yaris",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 83,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Yaris",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 84,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Yaris",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "185/60R15 84H",
            price: "₹0"
        },
        {
            id: 85,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Glanza",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "195/55R16 87V",
            price: "₹0"
        },
        {
            id: 86,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Glanza",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "195/55R16 87V",
            price: "₹0"
        },
        {
            id: 87,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Toyota",
            vehicle_model: "Glanza",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "195/55R16 87V",
            price: "₹0"
        },
    
        // Kia
        {
            id: 88,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Seltos",
            tyre_brand: "Apollo",
            tyre_model: "Apterra H/P",
            tyre_size: "215/60R17 96H",
            price: "₹0"
        },
        {
            id: 89,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Seltos",
            tyre_brand: "JK",
            tyre_model: "Ranger H/T",
            tyre_size: "215/60R17 96H",
            price: "₹0"
        },
        {
            id: 90,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Seltos",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/L 33",
            tyre_size: "215/60R17 96H",
            price: "₹0"
        },
        {
            id: 91,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Sonet",
            tyre_brand: "Apollo",
            tyre_model: "Apterra H/P",
            tyre_size: "215/60R16 95H",
            price: "₹0"
        },
        {
            id: 92,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Sonet",
            tyre_brand: "JK",
            tyre_model: "Ranger H/T",
            tyre_size: "215/60R16 95H",
            price: "₹0"
        },
        {
            id: 93,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Sonet",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/L 33",
            tyre_size: "215/60R16 95H",
            price: "₹0"
        },
        {
            id: 94,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Carnival",
            tyre_brand: "Apollo",
            tyre_model: "Apterra H/P",
            tyre_size: "235/60R18 103H",
            price: "₹0"
        },
        {
            id: 95,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Carnival",
            tyre_brand: "JK",
            tyre_model: "Ranger H/T",
            tyre_size: "235/60R18 103H",
            price: "₹0"
        },
        {
            id: 96,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Kia",
            vehicle_model: "Carnival",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/L 33",
            tyre_size: "235/60R18 103H",
            price: "₹0"
        },
    
        // Renault
        {
            id: 97,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Kwid",
            tyre_brand: "Apollo",
            tyre_model: "Amazer 4G",
            tyre_size: "155/80R13 79T",
            price: "₹0"
        },
        {
            id: 98,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Kwid",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "155/80R13 79T",
            price: "₹0"
        },
        {
            id: 99,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Kwid",
            tyre_brand: "Bridgestone",
            tyre_model: "B290",
            tyre_size: "155/80R13 79T",
            price: "₹0"
        },
        {
            id: 100,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Kwid",
            tyre_brand: "Michelin",
            tyre_model: "Energy XM2",
            tyre_size: "155/80R13 79T",
            price: "₹0"
        },
        {
            id: 101,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Duster",
            tyre_brand: "Apollo",
            tyre_model: "Apterra HT2",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 102,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Duster",
            tyre_brand: "JK",
            tyre_model: "Ranger H/T",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 103,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Duster",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/T 684 II",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 104,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Renault",
            vehicle_model: "Duster",
            tyre_brand: "Michelin",
            tyre_model: "Primacy SUV",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
    
        // Nissan
        {
            id: 105,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Magnite",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "195/60R16 89H",
            price: "₹0"
        },
        {
            id: 106,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Magnite",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "195/60R16 89H",
            price: "₹0"
        },
        {
            id: 107,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Magnite",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "195/60R16 89H",
            price: "₹0"
        },
        {
            id: 108,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Magnite",
            tyre_brand: "Michelin",
            tyre_model: "Energy XM2",
            tyre_size: "195/60R16 89H",
            price: "₹0"
        },
        {
            id: 109,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Terrano",
            tyre_brand: "Apollo",
            tyre_model: "Apterra HT2",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 110,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Terrano",
            tyre_brand: "JK",
            tyre_model: "Ranger H/T",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 111,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Terrano",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/T 684 II",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 112,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Nissan",
            vehicle_model: "Terrano",
            tyre_brand: "Michelin",
            tyre_model: "Primacy SUV",
            tyre_size: "215/65R16 98H",
            price: "₹0"
        },
        {
            id: 113,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "EcoSport",
            tyre_brand: "Apollo",
            tyre_model: "Alnac 4G",
            tyre_size: "205/60R16 92H",
            price: "₹0"
        },
        {
            id: 114,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "EcoSport",
            tyre_brand: "JK",
            tyre_model: "UX Royale",
            tyre_size: "205/60R16 92H",
            price: "₹0"
        },
        {
            id: 115,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "EcoSport",
            tyre_brand: "Bridgestone",
            tyre_model: "Turanza T001",
            tyre_size: "205/60R16 92H",
            price: "₹0"
        },
        {
            id: 116,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Figo",
            tyre_brand: "Apollo",
            tyre_model: "Amazer 4G",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 117,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Figo",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 118,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Figo",
            tyre_brand: "Bridgestone",
            tyre_model: "B290",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 119,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Endeavour",
            tyre_brand: "Apollo",
            tyre_model: "Apterra AT2",
            tyre_size: "265/60R18 110H",
            price: "₹0"
        },
        {
            id: 120,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Endeavour",
            tyre_brand: "JK",
            tyre_model: "Ranger AT",
            tyre_size: "265/60R18 110H",
            price: "₹0"
        },
        {
            id: 121,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Endeavour",
            tyre_brand: "Bridgestone",
            tyre_model: "Dueler H/T 684",
            tyre_size: "265/60R18 110H",
            price: "₹0"
        },
        {
            id: 122,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Aspire",
            tyre_brand: "Apollo",
            tyre_model: "Amazer 4G",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 123,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Aspire",
            tyre_brand: "JK",
            tyre_model: "Vectra",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        },
        {
            id: 124,
            image: "https://www.mrftyres.com/images/tyres/patterns/perfinza-left_angle.png",
            vehicle_type: "Car",
            vehicle_brand: "Ford",
            vehicle_model: "Aspire",
            tyre_brand: "Bridgestone",
            tyre_model: "B290",
            tyre_size: "175/65R14 82T",
            price: "₹0"
        }
];

export default Cars;
